// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Segunda4F.Data;

#nullable disable

namespace Segunda4F.Migrations
{
    [DbContext(typeof(DirectorioDBContext))]
    [Migration("20260526012134_NullableTipoCliente0")]
    partial class NullableTipoCliente0
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Segunda4F.Data.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TipoClienteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Segunda4F.Data.ClienteInteres", b =>
                {
                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("InteresId")
                        .HasColumnType("int");

                    b.HasKey("ClienteId", "InteresId");

                    b.HasIndex("InteresId");

                    b.ToTable("ClienteIntereses");
                });

            modelBuilder.Entity("Segunda4F.Data.Interes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Intereses");
                });

            modelBuilder.Entity("Segunda4F.Data.TipoCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoClientes");
                });

            modelBuilder.Entity("Segunda4F.Data.Cliente", b =>
                {
                    b.HasOne("Segunda4F.Data.TipoCliente", "TipoCliente")
                        .WithMany("Clientes")
                        .HasForeignKey("TipoClienteId");

                    b.Navigation("TipoCliente");
                });

            modelBuilder.Entity("Segunda4F.Data.ClienteInteres", b =>
                {
                    b.HasOne("Segunda4F.Data.Cliente", "Cliente")
                        .WithMany("ClienteIntereses")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Segunda4F.Data.Interes", "Interes")
                        .WithMany("ClienteIntereses")
                        .HasForeignKey("InteresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Interes");
                });

            modelBuilder.Entity("Segunda4F.Data.Cliente", b =>
                {
                    b.Navigation("ClienteIntereses");
                });

            modelBuilder.Entity("Segunda4F.Data.Interes", b =>
                {
                    b.Navigation("ClienteIntereses");
                });

            modelBuilder.Entity("Segunda4F.Data.TipoCliente", b =>
                {
                    b.Navigation("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
